{
  "test-data-paths": ["/gpfs/alpine/csc499/scratch/jerry.huang/gpt-neox/data/slim_pajama/test/all/sp_test"],
  "test-data-weights": [
    1.
  ],
  "valid-data-paths": [
    ["/gpfs/alpine/csc499/scratch/jerry.huang/gpt-neox/data/slim_pajama/val/all/sp_val"],
  ],
  "valid-data-weights": [
    [1.],
  ]
}
